-- do not mess with the order
require "jager.plugconf.lsp.mason"
require "jager.plugconf.lsp.treesitter"
require "jager.plugconf.lsp.lspsaga"
require "jager.plugconf.lsp.lspconfig"
require "jager.plugconf.lsp.null-ls"
require "jager.plugconf.lsp.dapui"
require "jager.plugconf.lsp.prettier"
require "jager.plugconf.lsp.markdown"
require "jager.plugconf.lsp.neodev"
require "jager.plugconf.lsp.cmp"
--[[ require "jager.plugconf.lsp.mini-completion" ]]
require "jager.plugconf.lsp.autopairs"
require "jager.plugconf.lsp.autotag"
require "jager.plugconf.lsp.symbols-outline"
require "jager.plugconf.lsp.tabnine"
