#!/bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &

# bspc monitor -d ⼀ ⼆ 三 四 五 六 七 ⼋ ⼏ ⼗
bspc monitor -d 1 2 3 4 5 6 7 8 9 0

xset r rate 250 50

xsetroot -cursor_name left_ptr

bspc config automatic_scheme alternate &
bspc config initial_polarity second_child &
bspc config focus_follows_pointer false &

bspc config window_gap          20 &
bspc config top_padding         36 &
bspc config bottom_padding      20 &
bspc config left_padding        20 &
bspc config right_padding       20 &
bspc config border_width        2 &
bspc config split_ratio         0.58 &

bspc config click_to_focus      true &
bspc config borderless_monocle  true &
bspc config gapless_monocle     true &

bspc rule -a mpv state=fullscreen focus=on border=off &
bspc rule -a alacritty state=floating focus=on border=off &
bspc rule -a Yad state=floating &
bspc rule -a scrcpy state=floating &
bspc rule -a polkit-gnome-authentication-agent-1 border=off state=floating &
bspc rule -a polkit-kde-authentication-agent-1 border=off state=floating &
bspc rule -a Timeshift-gtk border=off state=floating &
bspc rule -a telegram-desktop state=floating &
bspc rule -a lutris border=off state=floating &
bspc rule -a fcitx-config-gtk3 border=off state=floating &
bspc rule -a kdeconnect-indicator border=off state=floating &
bspc rule -a FLTK border=off state=floating & # weylus
bspc rule -a rog-control-center border=off state=floating focus=on &
bspc rule -a xdm-app border=off state=floating focus=on &
bspc rule -a "emacs" desktop='^3' follow=true state=fullscreen border=off focus=on &
bspc rule -a "emacsclient" desktop='^3' follow=true state=fullscreen border=off focus=on &

picom --experimental-backends &

sudo chmod a+rw /sys/class/backlight/amdgpu_bl0/brightness &

/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

~/.config/polybar/launch.sh &

# /usr/bin/nm-applet --indicator &

/usr/bin/dunst &

/usr/bin/emacs --daemon &

~/.local/bin/low-battery &

# fcitx -d &

# kdeconnect-indicator &

# rog-control-center &

~/.local/bin/wallpaper -bspwm -dunst -polybar -wall="/mnt/storage/wallpaper/nordic/111.png" &
