require "jager.plugconf.core.alpha"
require "jager.plugconf.core.webicons"
--[[ require "jager.plugconf.core.barbecue" ]]
require "jager.plugconf.core.barbar"
require "jager.plugconf.core.bufferline"
--[[ require("jager.plugconf.core.lualine") ]]
require "jager.plugconf.core.windline"
require "jager.plugconf.core.neoscroll"
require "jager.plugconf.core.nvim-tree"
require "jager.plugconf.core.telescope"
require "jager.plugconf.core.cmp"
require "jager.plugconf.core.toggleterm"
require "jager.plugconf.core.illuminate"
require "jager.plugconf.core.autopairs"
require "jager.plugconf.core.autotag"
require "jager.plugconf.core.nvim-surround"
require "jager.plugconf.core.comments"
require "jager.plugconf.core.tabnine"
require "jager.plugconf.core.gitsigns"
require "jager.plugconf.core.colorizer"
require "jager.plugconf.core.whichkey"
require "jager.plugconf.core.flash"
require "jager.plugconf.core.harpoon"
require "jager.plugconf.core.restclient"
require "jager.plugconf.core.symbols-outline"
require "jager.plugconf.core.todo-comments"
--[[ require "jager.plugconf.core.indent-mini" ]]
require "jager.plugconf.core.zenmode"
